### ISSUE TITLE
Withdraw error

### ISSUE THREAD

**Issue by CryptorClub** [3s3s/opentrade#102]
I got error while try to withdraw.
Withdraw error (2): Error: The wallet passphrase entered was incorrect.

I check passphrase from file /root/opentrade/server/modules/private_constants.js
in a command line with cmd
`examplecoind walletpassphrase LONG_passphrase_string 60`
and its correct!

**Comment by CryptorClub** [comment]
I try to setup exchange on another vps, encrypt wallet and got same error, when trying to withdraw.

**Comment by jonn4y** [comment]
have no issues here please answer the following so we can try and help you better:

1. in private_constants.js does it say LONG_passphrase_string 
2. is the wallet encrypted?
3. what kind of coin are you trying to withdraw from? is it a Dash fork?

**Comment by 3s3s** [comment]
Does you tried another pass phrase?  For example, try "123"

**Comment by CryptorClub** [comment]
@3s3s simpler passphrase with uppercase and lowercase symbols solve the issue. Symbols like !@#$% was fail to decrypt. Thank you!
@jonn4y thank you for attention to my issue!
