### ISSUE TITLE
Add Search Icon

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#106]
Add search icon on top of the wallet page for quick access to specific coin & Provide a checkbox to display only coins with balance "Hide zero balance" 
![nav_bar](https://user-images.githubusercontent.com/12738581/44615157-3bdd2980-a850-11e8-9276-3b3c382a5102.png)

**Comment by cryptonana** [comment]
@knkrth can you show your exhange link?

**Comment by knkrth** [comment]
This is not my exchange but you can visit https://altmarkets.cc/

**Comment by cryptonana** [comment]
@knkrth i face problem when order place 0.0000001 its show me this error

Bad order price ( price < 0.00001 ) ( 1e-8 < 0.00001 )

how can resolve this issue i edit index.js and change dust volume but still same issue

**Comment by knkrth** [comment]
Refer https://github.com/3s3s/opentrade/issues/141

**Comment by cryptonana** [comment]
@knkrth not resovle dear

**Comment by jonn4y** [comment]
@cryptonana commenting on every issue is not going to get you the answer, this issue has been solved before, try looking through the closed issues, or take a look at the code for submitOrder in orders.js
