### ISSUE TITLE
Final check error! (4) when adding sell order

### ISSUE THREAD

**Issue by hashbook** [3s3s/opentrade#107]
I came across this error "Final check error! (4)" when trying to add sell order.

`
INSERT INTO orders VALUES  ('1', 'Monoeci', 'sell', '1.90000000', '0.00001500', 'Bitcoin', '1535231965644', '%7B%7D', '1535231965644-1-0.847349704090586')
INSERT success
UPDATE balance SET balance="0", history="%5B%7B%22from%22%3A%22e281832e1cbc08e146307712a7493de7%22%2C%22to%22%3A%226c76195fd37c859931605051b00650f9%22%2C%22amount%22%3A1.9%2C%22time%22%3A1535229718774%2C%22action%22%3A%22set%22%2C%22balanceOld%22%3A0%2C%22balanceNew%22%3A1.9%7D%2C%22%5B%7B%5C%22amount%5C%22%3A-1.9%2C%5C%22time%5C%22%3A1535231965646%2C%5C%22action%5C%22%3A%5C%22order%5C%22%2C%5C%22balanceOld%5C%22%3A1.9%2C%5C%22balanceNew%5C%22%3A0%7D%5D%22%5D" WHERE coin="Monoeci" AND userID="1"
`

any1 can help?

**Comment by hashbook** [comment]
and also

```
INSERT INTO sessions VALUES  ('9zjiSIL5fJmDlzeHgbkjrjrAxGzs9hguiepXuzHDcjw%3D', '1535237292845', '1')
INSERT error: SQLITE_CONSTRAINT: UNIQUE constraint failed: sessions.token
UPDATE sessions SET time='1535237292847' WHERE token='9zjiSIL5fJmDlzeHgbkjrjrAxGzs9hguiepXuzHDcjw%3D'
```

**Comment by daygle** [comment]
I am receiving a similar  error too after the recent change 'Final check error! (5)'.

**Comment by daygle** [comment]
@hashbook I am using Aug 17, 2018 in fact. Hopefully @3s3s corrects this ASAP.

**Comment by hashbook** [comment]
@jonn4y thank you.

**Comment by daygle** [comment]
@hashbook Mate, your bundling all your errors/issues in this case. Let's just focus on the final check error with this case.

Are you suggesting the missing car is causing this?

**Comment by hashbook** [comment]
@daygle no, not at all. i just didn't want to open another issue.

**Comment by CryptorClub** [comment]
Also get final check error 5 after disable/enable withdraw and trading. With LTC pair - orders works. On Doge getting this error

**Comment by CryptorClub** [comment]
I just make withdraw and then deposit through the coupon and error gone

**Comment by CryptorClub** [comment]
And again get this error. I closed all opened orders, and put again without error. 
Mystic ))

**Comment by CryptorClub** [comment]
And again I got this error. ((

**Comment by CryptorClub** [comment]
One of registered users has negative balance. Before I delete transaction line in admin panel "last trades". Do I need to fill it?

**Comment by hashbook** [comment]
@CryptorClub what version do you use?

**Comment by CryptorClub** [comment]
@hashbook , Up to latest commit 
https://github.com/3s3s/opentrade/commit/2374221575f6ca9f50e78d58b957180be701d272

**Comment by parwezmansuri** [comment]
@CryptorClub  i get final check error 4

**Comment by 3s3s** [comment]
fixed in latest commit

**Comment by hashbook** [comment]
great! will test it out. tnx!
