### ISSUE TITLE
Support CryptoNote Coins

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#109]
Hi, Add support for cryptonote related coins. 

Reference: https://getmonero.org/resources/developer-guides/wallet-rpc.html

**Comment by aminaqi** [comment]
yes please add support for cryptonote coins

**Comment by 3s3s** [comment]
Too many changes need for adding cryptonote.

**Comment by knkrth** [comment]
@3s3s Can you create a module to convert cryptonote coin commands to json rpc 1.0 commands? So that there is no need to chance any code on the exchange just add a plugin to covert the commands.

**Comment by 3s3s** [comment]
There is not interested for me. May be someone will do it.

**Comment by jonn4y** [comment]
check this out, not looked into it myself but might possibly be able to use / modify this into a workable script

https://github.com/xaria-coin/xaria-walletd-rpc-js

**Comment by knkrth** [comment]
@jonn4y Thank you, I'll take a look into it.

**Comment by 3s3s** [comment]
This is https://github.com/3s3s/opentrade/blob/master/server/modules/users/wallet.js#L12
getaccountaddress
getbalance
gettransaction
listtransactions
walletpassphrase
sendfrom
move
