### ISSUE TITLE
Remaining Confirmations - Wallets Page

### ISSUE THREAD

**Issue by daygle** [3s3s/opentrade#110]
A suggestion if I may.

I think we need to implement a confirmations column on the wallets page. So this would show the user how many confirmations are remaining before funds are credited to their account.

**Comment by jonn4y** [comment]
Just added a push for something similar here:

https://github.com/3s3s/opentrade/pull/122

you could maybe expand on that

**Comment by TheRealHotSwap** [comment]
Looks like this was added to the newest commit, i think we can close this @daygle
