### ISSUE TITLE
convert to techan.js chart

### ISSUE THREAD

**Issue by Thedabest** [3s3s/opentrade#111]
http://bl.ocks.org/andredumas/edf630690c10b89be390

**Comment by TheRealHotSwap** [comment]
This would be awesome! Has anyone attempted this?

**Comment by hashbook** [comment]
i had some time to play around. i replaced default charts with highstock charts. 

Will posted updated files as soon as I have more time (hopefully in next few days).

here you can see demo: https://orionbtc.com/market/BTC-XMCC

**Comment by hashbook** [comment]
https://github.com/hashbook/opentrade/commit/47d72dcba0e5ca65bc44abfa0be599259f72fccc
https://github.com/hashbook/opentrade/commit/0814c69c95dd4aea4bf5b7d0318f54dabc102bb4

design & charts as demo.
please not it is not finished yet. but good for testing.
charts will only work if main coin is BTC

**Comment by TheRealHotSwap** [comment]
damn, using DOGE pair. But ill take a look, thanks for putting this up.

**Comment by ZSmartDev** [comment]
nice

**Comment by ZSmartDev** [comment]
![image](https://user-images.githubusercontent.com/40519768/45745524-3692b500-bc2b-11e8-91b2-00f9aa4914c9.png)
Tks @hashbook

**Comment by hashbook** [comment]
yes, that's the general problem. i have same problem with buy/sell form where fee is displayed. i will make an update. if this would be php it would be easy for me (format_number ... to 8 digits) and it would work. since it's javascript i am lost :D but, i think i can make it work in future.

**Comment by ZSmartDev** [comment]
@hashbook 
https://github.com/3s3s/opentrade/blob/master/server/modules/users/orders.js#L521
Change to: https://pastebin.com/LqSuFfF6

Maybe it will help the numbers show full
Can you try it for me?
