### ISSUE TITLE
When i complete all step and run node main.js get error

### ISSUE THREAD

**Issue by parwezmansuri** [3s3s/opentrade#112]
root@vmi158022:~/opentrade/server# node main                
                                                            
/root/opentrade/server/main.js:3                            
const g_constants = require('./constants');                 
^^^^^                                                       
SyntaxError: Use of const in strict mode.                   
    at Module._compile (module.js:439:25)                   
    at Object.Module._extensions..js (module.js:474:10)     
    at Module.load (module.js:356:32)                       
    at Function.Module._load (module.js:312:12)             
    at Function.Module.runMain (module.js:497:10)           
    at startup (node.js:119:16)                             
    at node.js:902:3                                        
root@vmi158022:~/opentrade/server#

**Comment by CryptorClub** [comment]
Maybe command should be
'sudo node main.js'

**Comment by parwezmansuri** [comment]
Yes I also add Audi node main.js

**Comment by parwezmansuri** [comment]
Can you help me for installation

**Comment by knkrth** [comment]
@CryptorClub Hi, Can you push your UI changes to the main branch? So that @3s3s can update your changes.

**Comment by parwezmansuri** [comment]
Thanks

**Comment by parwezmansuri** [comment]
I am not able to run I do every thing but not work I get error when run sudo node main.js node_sqlite3.node cannot find module

**Comment by coinnetworkpw** [comment]
@parwezmansuri 
Your packages are not installed correctly, you need to install nodejs again.
cd to opentrade and follow those instructions - https://gist.github.com/vietlq/cf1903e778bbd76a80f46823b19f8f49

when you are done then just do sudo npm install in opentrade folder and everything should be installed and working.

**Comment by parwezmansuri** [comment]
Now I completed all step and successful install and run sudo node main.js then I get error SMTP response error code 554 I am using Ubuntu server on local machine.

**Comment by coinnetworkpw** [comment]
@parwezmansuri 

change noreply email into your domain name or ip (example: noreply@yourdomain.com or noreply@ip)

**Comment by parwezmansuri** [comment]
I get again error sending mail <buffer 43 6g.......
SMTP response error code 550

**Comment by knkrth** [comment]
@parwezmansuri Change https://github.com/3s3s/opentrade/blob/master/server/constants.js#L16 from `enabled` to `disabled `& run `sudo node main.js`

**Comment by parwezmansuri** [comment]
Coin trades GitHub not available

**Comment by parwezmansuri** [comment]
I get again same error after enable to disable sending mail <buffer 43 6g.......
SMTP response error code 550

**Comment by coinnetworkpw** [comment]
@knkrth no it's not because I used commercial theme to create this one and can't put it open source, not allowed.

**Comment by parwezmansuri** [comment]
I using my Gmail email id

**Comment by coinnetworkpw** [comment]
I don't know, I had the same problem and as soon as I added no-reply@cointrades.pw in noreply email it started working.

**Comment by CryptorClub** [comment]
@parwezmansuri on which error do you stuck?

**Comment by parwezmansuri** [comment]
I put support email = parwez@rediffmail.com
And no replay email = parwez@gmail.com

Then I run sudo node main.js I get error sending mail < buffer 45 6f ......
SMTP response error code 550

**Comment by CryptorClub** [comment]
You also need to be sure, that 25 port is opened/allowed by your VPS provider. On Digital Ocean, they restricted it by default, I create a ticket there with ask to open it.

**Comment by parwezmansuri** [comment]
I use ubuntu local computer with internet how can I open port in local
computer.

**Comment by jonn4y** [comment]
When I stated our exchange I had issues with the no rely being gmail when I changed it to a domain I owned it worked fine so change your no reply email

**Comment by parwezmansuri** [comment]
Need to buy hosting or only domain

**Comment by knkrth** [comment]
@parwezmansuri You need to buy domain only. If you don't have the domain just `disable` emailVerificationEnabled on https://github.com/3s3s/opentrade/blob/master/server/constants.js#L16 & you are good to go.

**Comment by knkrth** [comment]
```
exports.share = {
   tradeEnabled: true,
   recaptchaEnabled: true,
   emailVerificationEnabled: 'disabled', 
```

**Comment by parwezmansuri** [comment]
After disable then what I put on support email and noreply email .

**Comment by knkrth** [comment]
@parwezmansuri  After `disabled` you can leave the emails as it is. The email verification process is disabled so no need to worry.

**Comment by parwezmansuri** [comment]
I do that but same error of SMTP response error 550

**Comment by knkrth** [comment]
@parwezmansuri Just delete the opentrade folder & Follow the https://github.com/3s3s/opentrade/blob/master/readme.md instructions.

**Comment by parwezmansuri** [comment]
I completed all step again and I edit constants.js and disabled emailverification and after I run sudo node main.js I get error SMTP response error code 554

**Comment by knkrth** [comment]
@parwezmansuri Are you able to open the website https://localhost:40443 on the browser & Try registering a new user. If it works than you can ignore the SMTP error.

**Comment by parwezmansuri** [comment]
No working I try both ip and localhost

**Comment by knkrth** [comment]
Can you take the screen short by pressing `PrintScreen` & post it here.

**Comment by knkrth** [comment]
Just drag the picture & drop it on comment box.

**Comment by parwezmansuri** [comment]
SMTP error

On 04-Sep-2018 6:25 PM, "karthik" <notifications@github.com> wrote:

Can you take the screen short by pressing PrintScreen & post it here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/3s3s/opentrade/issues/112#issuecomment-418356109>, or mute
the thread

**Comment by parwezmansuri** [comment]
![smpt error](https://user-images.githubusercontent.com/33519897/45033120-3adaa200-b071-11e8-847b-ea2fa1aeab82.jpg)

**Comment by knkrth** [comment]
Set it to `true` https://github.com/3s3s/opentrade/blob/master/server/constants.js#L11 & post the out put.

**Comment by jonn4y** [comment]
error 554 is usually caused when the server you are emailing to rejects your email because it doesn't like how the header is formatted, 
when you start the server it sends  email notification to say the exchange has started successfully.

I had the same issue when i didnt setup SPF records for the domain i was using etc.

you say you have it setup like this:

I put support email = parwez@rediffmail.com
And no replay email = parwez@gmail.com

so when you start the exchange, the script sends an email to `parwez@rediffmail.com` from `parwez@gmail.com` when the email is received at rediffmail.com they will see the email came from your local computers IP NOT gmail.com and it rejects the email causing the error.

I think there is a way around it to use Gmail using their MX records or something (not sure how that would world on localhost) but using digital ocean i was able to set my VPS IP with my domain and link the SPF records then the issue went away.

Hope that helps

**Comment by jonn4y** [comment]
you really should be running this on a VPS like digital ocean and associate a domain name.
in your screenshot
Invalid DNS PTR record is what i was talking about above, your email is being rejected because your localhost `150.107.20.238` is sending an email pretending to be from your noreply email so its rejected.

**Comment by parwezmansuri** [comment]
ok when i put support and no reply email
I put support email = parwez@rediffmail.com
And no replay email = parwez@gmail.com
but site no working only i get this log please check screenshot
![web not working](https://user-images.githubusercontent.com/33519897/45035014-92c7d780-b076-11e8-9d67-7d3b406c88ac.jpg)

**Comment by aminaqi** [comment]
@coinnetworkpw can you please email me I need your help 
aminmr1375@gmail.com

**Comment by indianex** [comment]
Where to write the SMTP username , password , send from mail.... so that we can use mail to send when someone resets his password, I am not able to send the Confirmation mail.
How to setup the smtp settings ??
