### ISSUE TITLE
Display Daily Volume

### ISSUE THREAD

**Issue by jonn4y** [3s3s/opentrade#121]
Anyone got any idea on how to display the daily volume for a coin on the coin list on the left instead of the last volume, daily volume would be much better so i can convert it to BTC like most other exchanges use.

Any help appreciated.

**Comment by coinnetworkpw** [comment]
@jonn4y 
you can probably use 24h volume from chart stats

**Comment by jonn4y** [comment]
@coinnetworkpw its pulled via API and its too slow, i have also tried calling the following inside exports.UpdateMarket = function() in the file markets.js

`let dailyVol = '0.0';
		 const WHERE = 'coin="'+unescape(coin.name)+'" AND time > ('+Date.now()+'-24*3600*1000)';
		 console.log('before db call');
		 g_constants.dbTables['history'].selectAll('sum(fromSellerToBuyer) AS Volume', WHERE, 'GROUP BY coin', (err, rows) => {
			if (err || !rows)
			{
				onError(req, res, err && err.message ? err.message : 'unknown database error');
				return;
			}
	
			if (rows.length)
			{
				coin['dailyVolume'] = (rows[0].Volume*1).toFixed(8);
				console.log('dailyVolume: '+coin['dailyVolume']);

			}
	
		 });`


it works BUT it outputs AFTER the rest of the code has been run so never includes the 24hr volume

if you have any ideas im all ears

**Comment by coinnetworkpw** [comment]
@jonn4y 
I'm not in my office now but from what I see maybe we can do it by using g_History24

const msgc = {coins: data};
        g_History24 = msgc;
        
        // Broadcast to everyone else.
        const msgcString = JSON.stringify({request: 'market', daily: msgc});
        g_constants.WEB_SOCKETS.clients.forEach( client => {
            if (client.readyState === WebSocket.OPEN) 
                try {client.send(msgcString);} catch(e) {client.terminate();}

And the call it with daily.volume*1 insead of message.volume*1 since its broadcasted to all 
History24 will

**Comment by jonn4y** [comment]
@coinnetworkpw doing this would then not include all the data from 
require("./trade").GetLastCoinHistory(rows[i]);
which is needed for turning fields red / green on trades etc
but i think you may be on to something.

i did try and run a for loop like:

`
let volume = 0;
		for (let key in g_History24)
        {
        	if (key == rows[i].name) {
            	volume = g_History24[key].Volume*1;
            	rows[i].dailyVolume = volume;
            	console.log('ABCDEFG :coinName: '+rows[i].name+' VOLUME:'+volume);
            }
        }
`

so i could just pull the volume from g_History24 as it already has it stored but again the loop is too fast to get any info other than the last result from this for loop.

when you are in the office i would love to work with you on this if possible, my bet is a few people would like daily volume instead of last volume.

**Comment by TheRealHotSwap** [comment]
any updates on this? I too would like to see 24hour volume
