### ISSUE TITLE
OpenTrade Crashing (After Recent Update)

### ISSUE THREAD

**Issue by daygle** [3s3s/opentrade#129]
Is anyone else finding that OpenTrade is crashing around every 12 hours after the recent update?

**Comment by jonn4y** [comment]
mine has been fine for weeks no issues, have you got debugging enabled and checked the debug log to see what its doing when it crashes.

**Comment by daygle** [comment]
How do you turn the debugging on? The recent update doesn't seem to write to the debug log anymore'.

**Comment by jonn4y** [comment]
@daygle 

https://github.com/3s3s/opentrade/blob/master/server/constants.js#L11

set this to true and start it again

**Comment by daygle** [comment]
This is still happening, surely it's not just me? OpenTrade seems to stop without reporting errors in the log....

**Comment by jonn4y** [comment]
did you enable the debug log as above?

**Comment by daygle** [comment]
Seems to be related to running OpenTrade in a screen session. Stopped using screen.
