### ISSUE TITLE
Withdraw error: Block. Please contact support.

### ISSUE THREAD

**Issue by TheRealHotSwap** [3s3s/opentrade#130]
Did a full reinstall with a fresh server. When I attempt to withdraw I get this error on two different coins and even when I try to withdraw only half the coins.

Any ideas?

**Comment by CryptorClub** [comment]
I'm too get this error. I click "Fix" button in Admin panel before on currencies, that have block error, or amount too big.

**Comment by jonn4y** [comment]
Follow the code backwards.

https://github.com/3s3s/opentrade/blob/527cda857ec3a6d29a00b527dc520be716f3782e/server/modules/users/wallet.js#L693

If the withdraw amount is greater than the balance in the wallet the user gets blocked

Filling the code it adds a tag to the users info field in the database stopping them from withdrawing.
Goto the database to the users column and clear the info field. Should help

**Comment by TheRealHotSwap** [comment]
Thanks for the help! I’ll do that. 

Is there a good way to disable this? I can’t withdraw from that coin now. 

Say a customer made a mistake and entered an extra zero, they would need to contact support to have the block removed. I understand why it’s there but it should be temporary.

**Comment by CryptorClub** [comment]
I fix user balances, and amount for withdraw still to big.

**Comment by CryptorClub** [comment]
I modify DB line to:
`%7B%22role%22%3A%22Administrator%22%2C%22blockWithdraw%22%3Afalse%7D`
And withdraw in Dogecoin.
But still not withdraw to Fiat. Too big withdraw.

**Comment by TheRealHotSwap** [comment]
Got it figured out, thanks for the assistance!

**Comment by CryptorClub** [comment]
I still have this error, with not correct balances. One my user too
