### ISSUE TITLE
Chart not show?

### ISSUE THREAD

**Issue by Thedabest** [3s3s/opentrade#134]
Can you give me a sample of 30 days old sql and have a full chart?

**Comment by jonn4y** [comment]
Well you can view the charts on the main demo

http://trade.multicoins.org

or you can have a flick through my charts here:

https://altmarkets.cc/market/BTC-DOGE

i don't think anyone will give you their sql tho

**Comment by knkrth** [comment]
@jonn4y Your site UI is good can you share it with me? Here is my e-mail: gsrwallet@gmail.com or you can create a pull request for UI changes here.

**Comment by jonn4y** [comment]
Sorry that Ui has taken me many hours to make and has already been ripped off by another site causing confusion between some of our users.
It’s pretty simple to change with basic css or you could simply hire a designer to make some changes for you

**Comment by knkrth** [comment]
@jonn4y ok.

**Comment by jonn4y** [comment]
I am willing to help you a little if you like though with a few things

**Comment by knkrth** [comment]
@jonn4y Thank you but the default UI is ok with me. Do you know how to integrate `Ethereum` or `CryptoNote` related coins to the market?!

**Comment by Thedabest** [comment]
![image](https://user-images.githubusercontent.com/40519768/45804892-98185980-bce7-11e8-869f-bafa41545110.png)
now my chart are working tks you :P

**Comment by knkrth** [comment]
@jonn4y Ya, I found it https://github.com/DeV1doR/ethereumd-proxy Let me see weather it works or not & I let you know.

**Comment by knkrth** [comment]
@Thedabest Close this issue as it is resolved,

**Comment by jonn4y** [comment]
@knkrth thats the one, sorry was out otherwise would have linked it, let me know how it goes.
never really touched eth, is the blockchain size going to be an issue do you think or could you use a light wallet maybe?

**Comment by knkrth** [comment]
@jonn4y I don't know light wallet will work or not. ETH blockchain is more than 1 TB its not suitable for small market. Maybe we should try CryptoNote related coins & Leave ETH related coin.

**Comment by Thedabest** [comment]
#135 @jonn4y can you help me?

**Comment by jonn4y** [comment]
@Thedabest what do you need help with?

**Comment by KhobQc** [comment]
the main trade pair is showing chart but others dont 
at least 5 trades have ben made with 10 minutes interval

**Comment by rraallvv** [comment]
Has anyone tried the ethereumd-proxy?

@knkrth where did you get the Ethereum blockchain size? I've seen a couple of posts discussing about its size but can't find any official information. However I'm relying on [this one](https://etherscan.io/chart2/chaindatasizefast) which says its about 110 GB for fast sync mode.
