### ISSUE TITLE
 Cant place orders price with odd number

### ISSUE THREAD

**Issue by Thedabest** [3s3s/opentrade#135]
![image](https://user-images.githubusercontent.com/40519768/45833406-c4a39400-bd2e-11e8-956d-b1bddb695966.png)

**Comment by Thedabest** [comment]
cant place orders for less than 10 sts or less than 10 sts

**Comment by CryptorClub** [comment]
Do you try to change dust volume in constants.js file?

**Comment by Thedabest** [comment]
i change to DUST_VOLUME: 0.000000001,

And is it still possible to give me an example?

**Comment by Thedabest** [comment]
DUST_VOLUME: 0 
remain so...

**Comment by Thedabest** [comment]
![image](https://user-images.githubusercontent.com/40519768/45868296-88644800-bdaf-11e8-9330-bc58327dcac8.png)
Fixed
https://github.com/3s3s/opentrade/blame/c8d200b0c5feff927277de33d5c7b84cb5851721/server/utils.js#L47
