### ISSUE TITLE
Upgrade Admin Panel

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#151]
Upgrade admin panel with 24 hour trade volume & the exchange fee of total trade/day 

Prove a hot wallet option on add coin section to enter the altcoin address to collect the fee. We can use move option to collect all the fee on the specified wallet address.

And also provide ultimate access to administrator role. Simply everything to managed by a single person.

**Comment by knkrth** [comment]
Provide a option like `Minimal balance` in `Add Coin` section with the `Minimal trade limit` so that we can enter the trade volume from `0.00000001` to our desire volume.

**Comment by Tr0j4n9** [comment]
This can be worked on. If you do want this, Why dont you help and contribute?
