### ISSUE TITLE
 Orders that are less than or equal to 0.00000100 can not confirm

### ISSUE THREAD

**Issue by Thedabest** [3s3s/opentrade#153]
Orders that are less than or equal to 0.00000100 can not confirm

![image](https://user-images.githubusercontent.com/40519768/46003193-17d46880-c0da-11e8-8833-b68cf9f358b7.png)
tks all!

**Comment by Thedabest** [comment]
@3s3s can you help me?

**Comment by joenilan** [comment]
same problems as https://github.com/3s3s/opentrade/issues/141

**Comment by 3s3s** [comment]
> 
> 
> @3s3s can you help me?

Just change this constant https://github.com/3s3s/opentrade/blob/master/server/constants.js#L20

**Comment by x3c** [comment]
But won't changing the DUST constant also cause problems with coins that are worth a lot such as BTC, and make it necessary to be able to handle orders of maybe 0.000001 BTC... ?

**Comment by Thedabest** [comment]
Tks all :| i change DUST to 0.00000000001 and working normal ✌️
