### ISSUE TITLE
Request UI Fix/Upgrade

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#155]
Change the default copy button to https://clipboardjs.com/ Which is smooth & it won't popup any alert.

And every time deposit/withdraw/history click the popup scroll to the top & open, If I click deposit at the bottom most coin & close the popup I have to again scroll down to bottom to see the history/withdraw 

Open popup without scrolling to the top. 

Is it possible to display the chart with 0 trade. Empty chart space on a new coin doesn't seem right.

Increase the market tab width & reduce the chat tab width.

On buy/sell tab the total amount is not auto changing while entering the trade amount like (https://yobit.net/en/trade/LTC/BTC) It displays the total payable amount once we click on the side. 

Gradually improve the UI of the exchange.

**Comment by Thedabest** [comment]
Do it yourself

**Comment by knkrth** [comment]
@Thedabest I know that but If everyone use the default UI then it is easy to update the code if there is any bug fix or any other update . 

If I use a custom UI I have to compare two codes & manually update the source code.

In default UI I can just use `git pull origin master` & Everything is updated, Ready to go in a minute.

**Comment by Thedabest** [comment]
This is a very good UI template that is very easy to modify

**Comment by knkrth** [comment]
@jonn4y @CryptorClub @3s3s Does anyone figure out how to real time update the total amount in buy/sell section like other exchanges? 
![update](https://user-images.githubusercontent.com/12738581/48177934-48482d00-e33d-11e8-870a-e3cf8e6fd285.gif)

**Comment by jonn4y** [comment]
@knkrth one of the first things you learn with JS that one :)

change lines
https://github.com/3s3s/opentrade/blob/master/static_pages/js/index.js#L793
https://github.com/3s3s/opentrade/blob/master/static_pages/js/index.js#L796
https://github.com/3s3s/opentrade/blob/master/static_pages/js/index.js#L799
https://github.com/3s3s/opentrade/blob/master/static_pages/js/index.js#L802

from:
 `on('change', e => {`

to:
`.on('keydown', e => {`

thats how i did it on ours at AltMarkets

**Comment by Puual** [comment]
`.on('keydown' ,e => `

Gives strange behavior for me

I've chosen `input` instead of `keydown`. 
Works for me like I expect

**Comment by knkrth** [comment]
@jonn4y Thanks.
