### ISSUE TITLE
Mobile dropdown menu

### ISSUE THREAD

**Issue by TheRealHotSwap** [3s3s/opentrade#163]
I'd love to see a good mobile menu added, the current site doesn't work well with mobile.

**Comment by Tr0j4n9** [comment]
This is not supposed to work with mobile. It was made for desktops.

**Comment by CryptorClub** [comment]
https://github.com/3s3s/opentrade/blob/master/server/views/partials/header.ejs#L9
At this line add:
`<div class="collapse navbar-collapse" id="navbarSupportedContent">`

and after </ul>
`</div>`
