### ISSUE TITLE
Main page balance and orders doesn't show up

### ISSUE THREAD

**Issue by kokucrypto** [3s3s/opentrade#168]
As you can see,coins are deposited as show on wallet panel from admin page,but from second page, nothing show up, still loading for ever.
Randomly i put an order and the order wen thru, but still nothing appear in main page.

![immagine](https://user-images.githubusercontent.com/43569613/46906757-21970200-cf09-11e8-82f0-e88e8551548e.png)

![immagine](https://user-images.githubusercontent.com/43569613/46906748-f2809080-cf08-11e8-9152-218a64d2ac3a.png)
![immagine](https://user-images.githubusercontent.com/43569613/46906754-0926e780-cf09-11e8-8b91-0ca7f9298927.png)

**Comment by KhobQc** [comment]
how did you fixed it?

**Comment by KhobQc** [comment]
![image](https://user-images.githubusercontent.com/37352625/46919610-af2d2d00-cfaf-11e8-9f5d-07c2750c1219.png)
u get the same error

**Comment by TheRealHotSwap** [comment]
Getting the same issue now as well.

**Comment by kokucrypto** [comment]
In my case, i have migrated all to a new vps and powerful host and everything up to now looks stable
