### ISSUE TITLE
Fees questions

### ISSUE THREAD

**Issue by kokucrypto** [3s3s/opentrade#170]
Hi,

FIRST:
How to check all fees that ADMIN of exchange is collecting for every trade of all coins traded on exchange? 
And how eventually to withdraw fee from exchange to personal wallets?

SECOND:
Is there a way to set-up different fees for every pair? Or we can set-up only the variable TRADE_COMISSION: 0.001 on constants.js that will be applied for all pairs?

THIRD: (CLOSED)
I have deposited this amount of LTC, trying to witdraw, looks like fee deducted are 0.002 and not 0.001 as setted up on constants.js. Thoughts?

![immagine](https://user-images.githubusercontent.com/43569613/46917644-b3feda80-cfc9-11e8-8ba7-1ec294e89a8e.png)

**Comment by TheRealHotSwap** [comment]
I can answer two of your questions.

THIRD: When you added the coin there is an option for the minimum, it suggest 0.002. Change that particular coins transaction fee.

FIRST: Under the affiliates tab of the admin account you should see all the commissions.

**Comment by Guillerbr** [comment]
ok
