### ISSUE TITLE
Chat Admin issue (How to ban users from Admin area)

### ISSUE THREAD

**Issue by kokucrypto** [3s3s/opentrade#175]
Hi,

-User admin (first user) with all role tested:
Selecting ID users for ban, will result in : USER IS NOT ROOT

Thoughts?

![immagine](https://user-images.githubusercontent.com/43569613/47031870-2c53d000-d171-11e8-9149-3653541cc729.png)

**Comment by kokucrypto** [comment]
Fixed

**Comment by freakcoderz** [comment]
> 
> 
> Fixed

Having the same issue. How did you fix this?

**Comment by crackfoo** [comment]
Same here... any ideas to fix this?

Thanks

**Comment by moodscripted** [comment]
Going to have another go at this one. Will let you know.

**Comment by crackfoo** [comment]
Ideally you’d think the admin would already have access to all the
support/moderation pages but seems admin account can only do some core
things. Wish there was simply an option to allow admin all access. I can’t
even get the support role to show the support role pages...
