### ISSUE TITLE
many problems please fix signup withdrawal and balance

### ISSUE THREAD

**Issue by cryptonana** [3s3s/opentrade#179]
every thing install ok, but 
1- when signup its always show loading not redirect to login
2- when withdrawal only loading no thing happend
3- your balance show only loading some time work and some time only show loading

i attache screenshots
![loding](https://user-images.githubusercontent.com/40866572/47082128-867c8180-d1c1-11e8-912d-cded821413c7.png)
![signup](https://user-images.githubusercontent.com/40866572/47082130-867c8180-d1c1-11e8-9d2b-1df0de638add.png)
![withdrawal](https://user-images.githubusercontent.com/40866572/47082131-87151800-d1c1-11e8-96d8-dc7c534675db.png)

please tell me how can i fix this issue

**Comment by cryptonana** [comment]
@altmarkets dont warry i was set this just for fun i dont copy your sheet :) i will set my own i will launch site and show you

**Comment by gnark-mining** [comment]
> 
> 
> Did you enjoy taking the Stylesheet from us, Github is all about sharing and contributions especially with such an open source project.
> 
> But that takes the piss.
> 
> And you go further to ask for help?

So you're a dick even on github.  lol what a douche omg , crapy person for a crapy exchange, altmarkshit
