### ISSUE TITLE
Max referred users 50?

### ISSUE THREAD

**Issue by CryptorClub** [3s3s/opentrade#183]
You are currently registered as an affiliate for 50 users... Is written on Affiliate page a long time.
This count definitely is limited somewhere...

**Comment by CryptorClub** [comment]
![screenshot_2018-10-23 greencoin grn exchange](https://user-images.githubusercontent.com/15973525/47352563-d1ffc580-d6c2-11e8-8f2b-00f45b1a4901.png)

**Comment by jonn4y** [comment]
https://github.com/3s3s/opentrade/blob/master/server/modules/registration/profile.js#L12

Change the 50 limit or remove and restart
