### ISSUE TITLE
Withdrawal Error (3): JSON value is not a boolean as expected

### ISSUE THREAD

**Issue by daygle** [3s3s/opentrade#189]
We are currently running the DGC wallet with our exchange and when users attempt to withdraw they receive the below error:-

Withdrawal Error (3): JSON value is not a boolean as expected

Seems to be only related to DGC, has anyone else come across this? If so, what can be done to correct it?

**Comment by jonn4y** [comment]
Check the RPC command for sendfrom on the DSG wallet
It requires an extra variable passing in the withdraw code

A simple IF statement will help you.

**Comment by daygle** [comment]
@jonn4y The funny thing is there doesn't seem like there is any extra variables in the command. See below:-

digitalcoin-cli sendtoaddress "XwnLY9Tf7Zsef8gMGL2fhWA9ZmMjt4KPwg" 0.1

The above is an example suggested from the DGC wallet.

**Comment by daygle** [comment]
@jonn4y I have even sent coins using the above command and no issues.

**Comment by jonn4y** [comment]
That’s using command line it’s different to Jason RPC

**Comment by jonn4y** [comment]
wait, you have set it as a dash clone in your config haven't you? DGC is a dashpay clone so you will need to add it to the DashForks line in your constants.js

**Comment by jonn4y** [comment]
lomtax/digitalcoin
forked from dashpay/dash

https://github.com/lomtax/digitalcoin

Are we on about the same coin?

**Comment by daygle** [comment]
Yeah that's the one.

lomtax/digitalcoin

So what do you recommend? Turn on dash? How?

**Comment by daygle** [comment]
The Dash fork ended up fixing the issue. Thanks for your help.

**Comment by jonn4y** [comment]
glad it helped :)

**Comment by sourcefinder1986** [comment]
what is the solution for this problem? it occurs on scribe-wallet too....
