### ISSUE TITLE
bitcoin error

### ISSUE THREAD

**Issue by cryptonana** [3s3s/opentrade#192]
after bitcoind run i see this error

getaccountaddress is deprecated and will be removed in V0.18. To use this command, start bitcoind with -deprecatedrpc=accounts.

how can install old version

**Comment by cryptonana** [comment]
and one more issue when trade buy or sell its show error

Bad order price ( price < 0.00001 ) ( 1e-8 < 0.00001 )

i try change dust volume but still same

**Comment by CryptorClub** [comment]
Parallel issue: https://github.com/3s3s/opentrade/issues/159
