### ISSUE TITLE
Recapcha disabled error

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#193]
Unable to login/signup while changing it https://github.com/3s3s/opentrade/blob/master/server/constants.js#L18 to `false`  ![image](https://user-images.githubusercontent.com/12738581/47611891-d6e2c180-da94-11e8-930b-77b87b6dc291.png)

**Comment by CryptorClub** [comment]
Here I got same error. 
https://github.com/3s3s/opentrade/issues/95
That was 25 port closed...

**Comment by knkrth** [comment]
Recapcha is disabled. There is no need for any port's to open anyways I'm sure port 25 was open on my server.

**Comment by CryptorClub** [comment]
Do you already registered on your exchange? Or on this page system redirect you after you trying to register? Do you have any errors in terminal or debug log?

**Comment by knkrth** [comment]
I'm unable to signup it keeps saying `Recapcha disabled error ` It's freshly installed exchange.

**Comment by CryptorClub** [comment]
@knkrth I has exactly same problem. In my case script can't sent email and print: Something wrong. Show what your terminal prints.

**Comment by knkrth** [comment]
I disable the email verification too.

```
opentrade/server# node main.js 
SSL Proxy listening on port 40443
mx resolved:  [ { exchange: 'mx00.mail.com', priority: 10 },
  { exchange: 'mx01.mail.com', priority: 10 } ]
MX connection created:  mx00.mail.com
recv email.com>554-mail.com (mxgmxus008) Nemesis ESMTP Service not available
recv email.com>554-No SMTP service
recv email.com>554 invalid DNS PTR resource record, IP=104.248.239.127
SMTP responds error code 554
Error with your mail server: SMTP code:554 msg:554-mail.com (mxgmxus008) Nemesis ESMTP Service not available
554-No SMTP service
554 invalid DNS PTR resource record, IP=104.248.239.127
```

**Comment by CryptorClub** [comment]
I found what this error means:
https://forums.cpanel.net/threads/smtp-error-554-blocked-emails.595699/

Servers IP address blocked by recipient. You may try to register with gmail account.
