### ISSUE TITLE
Wrong buy sell display data

### ISSUE THREAD

**Issue by kokucrypto** [3s3s/opentrade#198]
![image](https://user-images.githubusercontent.com/43569613/48078097-17ef7a00-e1e9-11e8-82e6-d1703cf06b29.png)

it will write in my open order as 

![image](https://user-images.githubusercontent.com/43569613/48078183-2fc6fe00-e1e9-11e8-9220-2aefafba05d6.png)

Basically every order made at 3 satoshi, will be written with 2 satoshi instead of 3

1-2-4-5-6 works fine, only if i enter a value of 3.

Any ideas?

**Comment by jonn4y** [comment]
Also noticed this happens randomly too @3s3s 

i think its the math somewhere around here:
https://github.com/3s3s/opentrade/blob/c403833f8b50e5eba6bc3d138a090b615d04b3ae/server/utils.js#L52

if you look at this code example the output should be 0.00000003 but its outputting 0.00000002

https://www.w3schools.com/code/tryit.asp?filename=FWPAIHGL5DLB

and if you change the 0.00000003  to say 0.00000004 it outputs 0.00000004 correctly its only certain low numbers it outputs incorrectly

what are your thoughts @3s3s ?

**Comment by 3s3s** [comment]
By default, OpenTrade is rounding float values to the seventh decimal place. You can change thishttps://github.com/3s3s/opentrade/blob/c403833f8b50e5eba6bc3d138a090b615d04b3ae/server/utils.js#L47
on
decimals = 9;

**Comment by kokucrypto** [comment]
Thanks!!!!! @3s3s 

By change decimals from 8 to 9, orders prices now are going thru correctly.

The only issue that occoured now, after Decimals change, is that every order either from buy/sell placed at 1 satoshi, after fer seconds automatically disappear (like if there is a timeout somewhere).

If i'm quick by make a fast buy/sell at 1 satoshi, orders are recorded correctly, but if i leave orders, they disappear.

That's happened after Decimals change to 9 instead at 8 and only for 1 satoshi orders.

But i'm not sure this is related at 100% to this change on decimals.

**Comment by 3s3s** [comment]
Try to change this constant
https://github.com/3s3s/opentrade/blob/master/server/constants.js#L23
on 
0.000000001

**Comment by kokucrypto** [comment]
@3s3s 

Thank you

It works like a charm now
