### ISSUE TITLE
Chart value issue

### ISSUE THREAD

**Issue by kokucrypto** [3s3s/opentrade#209]
Hello,
After upgrading chart visualization, all value(OPEN-HIGH-LOW-CLOSE) are not show properly:

![immagine](https://user-images.githubusercontent.com/43569613/49041045-798d7d80-f1c4-11e8-9cff-e501b6ed3734.png)

That's the code added on api v1.js:

 if (rows[i - 1].fromBuyerToSeller/rows[i - 1].fromSellerToBuyer > rows[i - 1].price) {
                    const data = ([
                        rows[i].time*1,//time.toUTCString(),
                        (rows[i].fromBuyerToSeller/rows[i].fromSellerToBuyer*1).toFixed(8),
                        (rows[i - 1].fromBuyerToSeller/rows[i - 1].fromSellerToBuyer*1).toFixed(8),
                        (rows[i - 1].price*1).toFixed(8),
                        (rows[i - 1].fromBuyerToSeller/rows[i - 1].fromSellerToBuyer*1).toFixed(8),
			(rows[i - 1].fromSellerToBuyer*1).toFixed(8)
                    ]);
                    retData.push(data);
			}
		   else if (rows[i - 1].fromBuyerToSeller/rows[i - 1].fromSellerToBuyer == rows[i - 1].price) {
                    const data = ([
                        rows[i].time*1,//time.toUTCString(),
                        (rows[i].fromBuyerToSeller/rows[i].fromSellerToBuyer*1).toFixed(8),
                        (rows[i - 1].price*1).toFixed(8),
                        (rows[i - 1].price*1).toFixed(8),
                        (rows[i - 1].fromBuyerToSeller/rows[i - 1].fromSellerToBuyer*1).toFixed(8),
			(rows[i - 1].fromSellerToBuyer*1).toFixed(8)
                    ]);
                    retData.push(data);
			}
		   else {
                    const data = ([
                       rows[i].time*1,//time.toUTCString(),
                        (rows[i].fromBuyerToSeller/rows[i].fromSellerToBuyer*1).toFixed(8),
                        (rows[i - 1].price*1).toFixed(8),
                        (rows[i - 1].fromBuyerToSeller/rows[i - 1].fromSellerToBuyer*1).toFixed(8),
                        (rows[i - 1].fromBuyerToSeller/rows[i - 1].fromSellerToBuyer*1).toFixed(8),
			(rows[i - 1].fromSellerToBuyer*1).toFixed(8)
                    ]);
                    retData.push(data);

With this values, api display correct values, but chart simply disappear.
By adding to all fields toFixed(8)*1 charts works but the result it's as pics above.

Any idea?

I have 8 decimals and main currency BTC

**Comment by CryptorClub** [comment]
The reason why chart is disapear is in api publishing.
Try access to your api in browser: https://yourexchangedomain.com//api/v1/public/getcharts?market=BTC-DOGE
And you will see, that in second case is empty.

**Correct line, that publishing correctly:** `rows[i - 1].price.toFixed(8)*1`
**False line, that do not publishes:** `(rows[i - 1].price*1).toFixed(8)`

**Comment by kokucrypto** [comment]
I think main problem with highcharts is that it displat correctly value by adding 
(rows[i - 1].price*1).toFixed(8) or (rows[i - 1].price*1).toFixed(8)*1

But if you have 8 decimals, by means price of 1 satoshi, it doesn't work, it always display 9-e etc etc.
when prices are above 9 satoshi, 10 for example, it works. 
But under 10 satoshi, it doesn't.

**Comment by jonn4y** [comment]
i fixed that with this:

`
Highcharts.stockChart('container', {
         title: {
             text: null
         },

         xAxis: {
             gapGridLineWidth: 0
         },

         rangeSelector: {
 		 selected: 2,
             buttons: [{
                 type: 'hour',
                 count: 1,
                 text: '1h'
             }, {
                 type: 'day',
                 count: 1,
                 text: '1D'
             }, {
                 type: 'day',
                 count: 7,
                 text: '7D'
             }, {
                 type: 'month',
                 count: 1,
                 text: '1M'
             }, {
                 type: 'all',
                 count: 1,
                 text: 'All'
             }],
             selected: 2,
             inputEnabled: false
         },
         
 		 yAxis: {            
            labels: {
                formatter: function () {
                     return this.value.toFixed(8);
                }            
            }
        },
        
           tooltip: {
        formatter: function () {
            var s = '<b></b>';
            $.each(this.points, function () {
                s += '<br/>Open: ' + this.point.open.toFixed(8) + '';
                s += '<br/>High: ' + this.point.high.toFixed(8) + '';
                s += '<br/>Low: ' + this.point.low.toFixed(8) + '';
                s += '<br/>Close: ' + this.point.close.toFixed(8) + '';
            });

            return s;
        }
    }, 
 		legend: {
                     enabled: false
         },
 		
 		exporting: {
                     enabled: false
         },
 		plotOptions: {
  candlestick: {	
  			lineColor: '#E75162',    		
 	    	upLineColor: '#5BB789',
 	    	upColor: '#5BB789',
 	    	color: '#E75162'
         }
     },

         series: [{
             type: 'candlestick',
             name: coinsymbol,
             data: json_obj
         }]
     });

`

**Comment by kokucrypto** [comment]
Thanks @jonn4y will try now.
Please, take a look here: https://github.com/3s3s/opentrade/issues/205

i know you know how to solve

**Comment by kokucrypto** [comment]
I think some other values need to be specified:

Adding this:
 yAxis: {            
        labels: {
            formatter: function () {
                 return this.value.toFixed(8);
            }            
        }
    },

Charts disappear,adding this:


 tooltip: {
    formatter: function () {
        var s = '<b></b>';
        $.each(this.points, function () {
            s += '<br/>Open: ' + this.point.open.toFixed(8) + '';
            s += '<br/>High: ' + this.point.high.toFixed(8) + '';
            s += '<br/>Low: ' + this.point.low.toFixed(8) + '';
            s += '<br/>Close: ' + this.point.close.toFixed(8) + '';
        });

        return s;
    }
}, 

Tooltip disappear.

**Comment by jonn4y** [comment]
Not on my computer right now just goto altmarkets.cc/test.html and view source and copy it everyone else did 😂

**Comment by kokucrypto** [comment]
Now it works, by copying your source and a simple copy/paste :):):):):)

I was so gently to try to understand instead of just copy/paste :):):)

Anyway, thanks, whenever you have time and could/want answer ticket: #205 i appreciate.

Regards.
