### ISSUE TITLE
BTC-LTC and BTC-DOGE pairs 

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#216]
@3s3s The recent updates on the https://trade.multicoins.org (BTC-LTC and BTC-DOGE pairs) is not updated on the github, Can you update the github repo to the latest update?

**Comment by sp1k31973** [comment]
yes please

**Comment by knkrth** [comment]
@3s3s Is the any update coming up?

**Comment by ExchangeTime** [comment]
I am kinda sure he said he didnt have time to keep patching this? Why not code it yourself?

**Comment by 3s3s** [comment]
I no longer intend to commit new versions in open source. Sorry.

**Comment by knkrth** [comment]
@3s3s Why? Can you email (gsrwallet@gmail.com) me the updated version?

**Comment by diakas** [comment]
me to, please :)

**Comment by ExchangeTime** [comment]
You guys think this guy will keep giving you newer versions for free when he is trying to build his own exchange? Atleast offer him payments for newer code or code it yourself. He just told you. "new versions in open source. Sorry". This means he wont share the new code with either of you.

@diakas @knkrth

**Comment by khay12** [comment]
USELESS open source project .  i go to Rubykube hehe 
![bitaltcoinexchange](https://user-images.githubusercontent.com/36717883/50374725-eb26e300-062d-11e9-9958-518f1d4f16ce.png)

**Comment by knkrth** [comment]
@khay12 Can you add new coin via json rpc on [rubykube](https://github.com/rubykube)?

**Comment by knkrth** [comment]
@3s3s Does the latest update contain BTC-LTC and BTC-DOGE pairs? If not, Can you provide it?

**Comment by ExchangeTime** [comment]
@knkrth Code it yourself, aint that hard. As he said before he wont share new patches. 
***I no longer intend to commit new versions in open source. Sorry.*** //3s3s
