### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by feltoxXx** [3s3s/opentrade#223]
Hi people, any help on this???

After npm install and doing the two start main.js

**Comment by knkrth** [comment]
Change this line  https://github.com/3s3s/opentrade/pull/219/files & you are good to go

**Comment by feltoxXx** [comment]
Nothing... same problem...

in the debugxxxxxxxxx.log says this: Error: SQLITE_CANTOPEN: unable to open database file


the script do not generate this file... i create one and nothing happens...

**Comment by knkrth** [comment]
Refer to #218 Change the database path to your local path.

**Comment by feltoxXx** [comment]
finally i have to change the line to explain in #218 but i have to create the database folder too... the existing one is not been read by the script

**Comment by knkrth** [comment]
Close this issue if its solved.
