### ISSUE TITLE
Async Function Failing After Update

### ISSUE THREAD

**Issue by daygle** [3s3s/opentrade#226]
Getting the below error after the recent git update - anyone have any suggestions on how to fix?

/root/opentrade/server/database.js:161
exports.Init = async function(callback)
                     ^^^^^^^^
SyntaxError: Unexpected token function

**Comment by ExchangeTime** [comment]
@daygle @midotrung Its explains the errors very simple there.
@daygle  you got a js wrong. (even says which).
@midotrung I guess u messed up with your SSL settings or you are using a SSL (apache) or something else using port 443. 

if you dont coding you shouldnt create a exchange as there will be security isseus.

**Comment by daygle** [comment]
@ExchangeTime The js is the same as the latest commit... Have you got this working?

**Comment by ExchangeTime** [comment]
@daygle Ofc i got this working. 

/root/opentrade/server/database.js:161
exports.Init = async function(callback)

Its explains where the error is. Follow it and look for errors that uses the script.
