### ISSUE TITLE
Hack proof

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#235]
Does the updated source is hack proof? Because the old source code lead to the hacking on the exchange using opentrade source code.

**Comment by EXLLY** [comment]
Hello

The code is still vulnerable and is not at all reliable. 

We have been the victim of add balance for Bitcoin and Litecoin in wallet of the exchange platform but no deposit for the Bitcoin or Litecoin on servers. 

At all 100 Litecoin and 200 Bitcoin. We are trying to retrieve the IP address of the user. 

we have deactivated withdrawals and we are currently sending emails to users with real funds to withdraw them.

 we will close the platform. 

It is urgent to fix this problem in the source code or to warn that the code is 

https://exlly.com/

**Comment by knkrth** [comment]
@EXLLY Thank you for your response. I hope @3s3s will fix this issue soon.

**Comment by knkrth** [comment]
Refer to #236
