### ISSUE TITLE
Difficulty loading after last update

### ISSUE THREAD

**Issue by CryptoCloudInc** [3s3s/opentrade#239]
node start main.js

returns, 

module.js:487
    throw err;
    ^

Error: Cannot find module '/root/opentrade/server/start'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

Are you testing before you push and updating the readme accordingly?

**Comment by CryptoCloudInc** [comment]
thats what was ran, but it throws the above assertion

**Comment by 3s3s** [comment]
or 
node main.js
or
forever start main.js

**Comment by CryptoCloudInc** [comment]
> or
> node main.js
> or
> forever start main.js

If you run forever start main.js , nothing loading.   If you run node main.js you get the above assertion.

All dependancies in place and error began after last update

**Comment by CryptoCloudInc** [comment]
node main.js returns:

root@Singapore:~/opentrade/server# node main.js
SSL Proxy listening on port 443
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:40543
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

so,

forever start main.js yields nothing

**Comment by 3s3s** [comment]
Run database server in separate console and you should see some logs: why database server refused connections.

**Comment by CryptoCloudInc** [comment]
Just had done that as your replied.

Heres the log

onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
onWebSocketConnection
{ dbPath: '/root/opentrade/server/database/sqlite.db',
  command: 'init',
  dbStructure: 
   { dbTables: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     dbIndexes: [ [Object], [Object], [Object] ] } }
{ dbPath: '/root/opentrade/server/database/sqlite.db',
  command: 'sql',
  sql: 'CREATE TABLE IF NOT EXISTS KeyValue (key TEXT UNIQUE PRIMARY KEY, value TEXT)' }
Error: SQLITE_CANTOPEN: unable to open database file
Node NOT Exiting...

**Comment by 3s3s** [comment]
mkdir /root/opentrade/server/database

**Comment by CryptoCloudInc** [comment]
already present....

I did a fresh clone in just to make sure I'm not crazy.

From the databaseServer or server, running :
```
node main.js
```
Returns,

root@Singapore:~/opentrade/databaseServer# node main.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/opentrade/databaseServer/main.js:7:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
root@Singapore:~/opentrade/databaseServer# 

I don't think the latest build is correct

**Comment by 3s3s** [comment]
npm install

**Comment by CryptoCloudInc** [comment]
Got it to run again,

I think the readme could use a once over again though.

We have an index coin we are wanting to work with on this platform.   Are you able to tell me how to get rid of the Marycoin pricing data and replace the banner pricing with our coins pricing easily? 

Also, I will change my issue to a less serious Headline if possible, but the readme should get a look over IMO

**Comment by CryptoCloudInc** [comment]
Issue resolved

**Comment by ExchangeTime** [comment]
@CryptoCloudInc I would advise you to not host a exchange incase you dont even know how to switch a currency.

**Comment by CryptoCloudInc** [comment]
We closed this issue and yet here you are trying to belittle.  why?
