### ISSUE TITLE
Withdrawal Error (3): JSON value is not a boolean as expected 

### ISSUE THREAD

**Issue by sourcefinder1986** [3s3s/opentrade#244]
Hi,
i saw there are already 2 issues of this closed, but i dont see the solution there?

Please give me short info how to solve this.
thanks!

**Comment by 3s3s** [comment]
Add ticker to this array https://github.com/3s3s/opentrade/blob/master/server/constants.js#L224

**Comment by sourcefinder1986** [comment]
thanks
