### ISSUE TITLE
Error: events.js:167

### ISSUE THREAD

**Issue by DigitalCoin1** [3s3s/opentrade#245]
In cd ~/opentrade/server && sudo node main.js:

> events.js:167
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Client network socket disconnected before secure TLS connection was established
>     at TLSSocket.onConnectEnd (_tls_wrap.js:1086:19)
>     at Object.onceWrapper (events.js:273:13)
>     at TLSSocket.emit (events.js:187:15)
>     at endReadableNT (_stream_readable.js:1094:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> Emitted 'error' event at:
>     at ClientRequest.req.on (/home/spero/opentrade/node_modules/ws/lib/websocket.js:552:10)
>     at ClientRequest.emit (events.js:182:13)
>     at TLSSocket.socketErrorListener (_http_client.js:392:9)
>     at TLSSocket.emit (events.js:182:13)
>     at emitErrorNT (internal/streams/destroy.js:82:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

In cd ~/opentrade/databaseServer && sudo node main.js

> ERROR: not allowed ::ffff:45.2XX.XXX.XXX

**Comment by 3s3s** [comment]
Change this line https://github.com/3s3s/opentrade/blob/master/server/modules/private_constants.js#L23
add your IP addres (45.2XX.XXX.XXX)

**Comment by DigitalCoin1** [comment]
Works!!!
