### ISSUE TITLE
Deposit not work ?

### ISSUE THREAD

**Issue by tasohagroup** [3s3s/opentrade#25]
It's fine overall except the deposit function, it seems like it's not working. I tried to deposit and fought the deposit history in account's wallet, but can't plus money and the pending money didn't display. 
I found in balance table, inserted some information and it looks like the balance was added. But i don't understand what are 2 columns of history and info in balance table mean? Please help. 
Thank you.

**Comment by 3s3s** [comment]
Try it with new commit. There was bug and I have fixed it

**Comment by tasohagroup** [comment]
i updated new comit , but i dont see change , deposit balances is moved to account of admin but not add balances for account deposit

**Comment by tasohagroup** [comment]
and error /root/opentrade/server/utils.js:17
  balance_log_file(util.format(d) + '\n');
  ^

TypeError: balance_log_file is not a function
