### ISSUE TITLE
Cannot read property 'ticker' of undefined

### ISSUE THREAD

**Issue by o-ayoub** [3s3s/opentrade#259]
Hello, After i have added a pairs, I have got this error: 

![valid](https://user-images.githubusercontent.com/27408905/56092986-59343600-5ebb-11e9-9ee3-bcb4c08d0672.png)

How can be  fixed ? 
Thanks

**Comment by o-ayoub** [comment]
fixed

**Comment by rohini4336** [comment]
i git same error.how to fix it?

**Comment by ARYACyperts** [comment]
> fixed

hey can you share info how to fix this issue
