### ISSUE TITLE
Accounts Server Guide

### ISSUE THREAD

**Issue by daygle** [3s3s/opentrade#261]
I have noticed a new accounts server component has been added to opentrade.

Would you happen to have a guide on how to setup? Or is this component still in progress?

I have attempted to access but no page is displayed when navigating to port 40745.

Has anyone else got this working?

**Comment by 3s3s** [comment]
Accounts server will work as a proxy between OpentTrade and coin daemons
This feature is not completed yet

**Comment by daygle** [comment]
Thanks for letting me know, look forward to seeing it once completed.
