### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Brewin95** [3s3s/opentrade#276]
Cannot GET /

**Comment by Brewin95** [comment]
when restarting forever I get 

Cannot GET / on page

**Comment by Brewin95** [comment]
Fixed

**Comment by CrissCrypto** [comment]
> 
> 
> Fixed

how did you fix it ?

**Comment by sohuynnamito** [comment]
How?

**Comment by djdeniro** [comment]
Rofl, but it not work!)

пн, 4 нояб. 2019 г., 12:59 sohuynnamito <notifications@github.com>:

**Comment by HugoPhoenix** [comment]
how did you fix it ?
