### ISSUE TITLE
Deposit for BTC 

### ISSUE THREAD

**Issue by IZEM-Project** [3s3s/opentrade#290]
Hello,

Thank you for this open source.

I have done this installation according to instructions provided and everything works fine.

I have a problem when I want to deposit for BTC when clicking on the Deposit button it will display - Method not found.

Help me to solve this problem.

**Comment by 3s3s** [comment]
Hi
the newest bitcoin version is not supporting accounts RPC. Try to use bitcoin 0.16.

**Comment by IZEM-Project** [comment]
Thanks

ok solve for BTC

now market pair only in BTC-LTC, how to add more market pair like MYCOIN-BTC or other altcoin?

**Comment by 3s3s** [comment]
In opensource version only one main coin is available (BTC or LTC or YOURCOIN etc). By default main coin is MC (Marycoin)

**Comment by IZEM-Project** [comment]
ok,

I made a deposit then I made a withdrawal but the balance did not show the latest balance change.

**Comment by 3s3s** [comment]
Looks like a bug

**Comment by IZEM-Project** [comment]
how to solve it?

**Comment by 3s3s** [comment]
I dont know. I do not have that

**Comment by IZEM-Project** [comment]
ok try find it
