### ISSUE TITLE
Balance of the fictional account

### ISSUE THREAD

**Issue by zoowcoin** [3s3s/opentrade#291]
I have an exchange account with a problem, the account has a part of the fictitious balance. How can I fix?

**Comment by 3s3s** [comment]
Try fix it in admin panel.

**Comment by zoowcoin** [comment]
how?

**Comment by 3s3s** [comment]
1. login as admin
2. go to "Admin Area" - "Users"
3. Find user by login and copy the first integer (user id)
4. go to "Admin Area" - "Check Balance" and find all balances by user id
5. click the button "Fix balance"

**Comment by zoowcoin** [comment]
I did it but it does not do anything. Yesterday I made a withdrawal but this appeared in the history, the withdrawal came to the wallet, but for some reason was added to the account of the exchange fictitious without being.
![error](https://user-images.githubusercontent.com/47944643/59853790-df647100-9371-11e9-8e9b-68caf2a8164e.jpg)

**Comment by zoowcoin** [comment]
send to the exchange wallet to cover that fictitious balance but I do not recognize it

**Comment by IZEM-Project** [comment]
your problem same like me.. old data does not change and only shows the same number even if it has been withdrawn

**Comment by zoowcoin** [comment]
Now the deposits do not work and also in the withdrawals it says that there is not enough balance. Urgent! What can be done?

**Comment by 3s3s** [comment]
Seems because you have deleted your wallet.dat for zoow
transactions from old wallet is saved in accountserver so if you need to
renew wallet.dat then you should
1. stop the accountserver
2. delete sqlite_accounts.db
3. start the accountserver and wait till new database will filled wirh
new transactions.
4. after all, you need to fix all balances manually throw the admin panel

**Comment by IZEM-Project** [comment]
I have tried this way but become a disorder.
where I check the coin-cli getbalance is true. but when I check the coins of the account getbalance. he points to incorrect number ..
what happens in wallet.dat or sqlite.db?

**Comment by zoowcoin** [comment]
No working, this same problem

**Comment by IZEM-Project** [comment]
I have encountered this problem ..
It concerns coind's name.

When you register a coin in the form you need to use the coin name by coind name.

You can not use abbreviated names as they cause RPC command errors.

example:
coinextrad
you need to fill in the name on the add coin form is COINEXTRA
you can not shorten the name.
