### ISSUE TITLE
How to delete confirmations

### ISSUE THREAD

**Issue by zoowcoin** [3s3s/opentrade#294]
How this replenishment is supposed to be updated and does not work correctly because it only makes fictitious balance appear or the deposits do not arrive and neither does it allow to withdraw.

https://github.com/3s3s/accountsserver

I would like to know how to eliminate this part of confirmations.
![error](https://user-images.githubusercontent.com/47944643/59968993-c14e6a80-9543-11e9-8292-534a198c5902.jpg)

**Comment by IZEM-Project** [comment]
this is blockchain info.. can not delete it..

**Comment by zoowcoin** [comment]
I already did it, now balances, deposit and perfect retirement.

**Comment by IZEM-Project** [comment]
can you show me how to fix it?

after withdraw the balance not update

**Comment by IZEM-Project** [comment]
deposit - ok
trade - ok
withdraw -  balance still not update
