### ISSUE TITLE
Litecoin version

### ISSUE THREAD

**Issue by IZEM-Project** [3s3s/opentrade#298]
Hello,

I want to add Litecoin .. I tried version 0.17.0 but like no support for rpc 1.0. What appropriate version can be installed?

Thanks

**Comment by zoowcoin** [comment]
Hi

In litecoin.conf you add:

rpcuser=xxxxxx
rpcpassword=xxxxxx
rpcallowip=127.0.0.1
rpcport=48081
deprecatedrpc=accounts <---------------- You add this.
rpcclienttimeout=10
server=1
daemon=1
upnp=0
rpcworkqueue=1000
enableaccounts=1
litemode=1
staking=0

**Comment by IZEM-Project** [comment]
Thanks @zoowcoin
