### ISSUE TITLE
Recent transactions not update

### ISSUE THREAD

**Issue by IZEM-Project** [3s3s/opentrade#299]
![Screenshot (16)](https://user-images.githubusercontent.com/46192778/60382639-8c3c9d80-9a98-11e9-9132-6901ec18f2ed.png)

Hello guys,

I need your help either paid or sincerely to help solve the problem I encountered:

1. Recent transactions are not updated:
when the deposit even blocks have matured it still shows 1/6 the confirmation.

2. Recent transactions are not updated:
When the withdrawal process has been made and no data shows the withdrawal transaction.

3. Withdraw transactions do not work well:
After doing the withdraw the balance shows the same amount even though the coin has managed to get out of the wallet and as long as it reaches its destination.

Please help me resolve this issue.

Best Regards
IZEM

**Comment by zoowcoin** [comment]
I did not update the account server directory, I left it as it is in the installation, then I deleted the confirmations section and now everything is going very well for me.

**Comment by IZEM-Project** [comment]
where to delete it?

**Comment by zoowcoin** [comment]
![zwexchange](https://user-images.githubusercontent.com/47944643/60389307-9c1ba800-9abf-11e9-92dc-240a7833967f.png)

**Comment by IZEM-Project** [comment]
but i get error when do withdraw.. my balance still same after withdraw..

**Comment by zoowcoin** [comment]
Avoid using this directory, it does not update correctly, there are many errors that have not been corrected.

https://github.com/3s3s/accountsserver

I even tried the new update and they returned the fictitious balance, the withdrawals did not work, the wallets appeared an internal error message, try it later ...

I preferred to make it practical, I went back to how it is now

**Comment by IZEM-Project** [comment]
u mean just run forever in server and dataServer?

**Comment by zoowcoin** [comment]
You Use this: https://github.com/3s3s/accountsserver/tree/9274a05996258c2607105e2cf9d8c302798b0c9e

Just change and modify the file. https://github.com/3s3s/accountsserver/blob/9274a05996258c2607105e2cf9d8c302798b0c9e/constants.js

this section:  const DATABASE_PATH = '/home/opentrade/accountsServer/database/sqlite_accounts.db'; by const DATABASE_PATH = '/root/opentrade/accountsserver/database/sqlite_accounts.db';

**Comment by IZEM-Project** [comment]
after remove accounts server and replace with new forever cant start

**Comment by IZEM-Project** [comment]
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/opentrade/node_modules/ws/index.js:3:19)

**Comment by zoowcoin** [comment]
you have to add all the contents of accountserver

**Comment by IZEM-Project** [comment]
Owesome... Thank you very much @zoowcoin all running good now....
May God bless you ..

**Comment by IZEM-Project** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/46192778/60390072-b164f680-9b00-11e9-9d49-1e7c67d9d4b3.png)

**Comment by IZEM-Project** [comment]
but withdraw not solve.. how to solve it?
balance still not update and still same after witdraw..

**Comment by IZEM-Project** [comment]
what you add list into pivx.conf?

**Comment by IZEM-Project** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/46192778/60390524-30f7c300-9b0b-11e9-946d-64a5f5023d31.png)

After withdraw nothing happen, the amount still same..

**Comment by zoowcoin** [comment]
After making these changes, have you deleted the database and restarted the entire exchange?

**Comment by IZEM-Project** [comment]
yes, i see is problem with my coin rpc function

if i do coin-cli move "test" "test2" 100

coin-cli listaccount
{
"" : ,
"test" = 500,      Good! Value Change
"test2" = 600,
}

but when i do coin-cli sendfrom "test" "AddressAKSNSNJJWNWJNWJ" 100
coin-cli listaccount
{
"" : -100,
"test" : 500,   Wrong!!! Value by account not change but get negatif in "" : -100
"test2": 600,
}

what i need to do for mycoin?? problem is from this.. manual test

**Comment by IZEM-Project** [comment]
i hava set 
enableaccount=1
staking=0
in mycoin.conf

**Comment by zoowcoin** [comment]
you add coin bitcoin principal

**Comment by IZEM-Project** [comment]
what you mean? not understand

**Comment by IZEM-Project** [comment]
my coin fork from esbcoin, i dont know what true add in coin.conf

**Comment by zoowcoin** [comment]
you coin is rpc 1.0?

**Comment by IZEM-Project** [comment]
my coin have listed at Enmanet and running good, Enmanet using OpenTrade to.. i dont think so if edit rpc command before compile.

**Comment by IZEM-Project** [comment]
my coin not working with command rpc sendfrom for withdraw. no recieve txid because output from main wallet.

**Comment by IZEM-Project** [comment]
i get this error for mycoin, insert data error to datatable

INSERT INTO sessions VALUES  ('hex+XXXX', 'time', '1')
INSERT error: undefined

whats need i do??

**Comment by zoowcoin** [comment]
Opentrade only works with coins that have rpc 1.0

**Comment by zoowcoin** [comment]
If your coin does not use rpc 1.0 it is not accessible for the exchange. If enmanet works and uses opentrade, the reason is because the developer himself made opentrade accessible.

**Comment by IZEM-Project** [comment]
okey.. i need to learn how to add rpc command for mycoin..

Thank so much for your support and reply..

Best Regards

close
