### ISSUE TITLE
method getaccoountadress not working

### ISSUE THREAD

**Issue by christophergidlof** [3s3s/opentrade#308]
method getaccountaddress not working when trying to deposit BTC 

getaccountaddress "account"

DEPRECATED. Returns the current Bitcoin address for receiving payments to this account.

**Comment by 3s3s** [comment]
Try to update accountserver to the latest version
cd ~/opentrade/accountsserver
forever stop main.js
git checkout master
git pull
forever start main.js

**Comment by christophergidlof** [comment]
that fixed it thanks

**Comment by christophergidlof** [comment]
marycoin stop working with updated accountserver give Unknown error/ Please try later
