### ISSUE TITLE
deposit button wont work

### ISSUE THREAD

**Issue by christophergidlof** [3s3s/opentrade#310]
hi deposit funds wont work gives error "Unknown error/ Please try later"

it works for a while if i  stop accountserver and start it again it works 

so for example trader account 1 try to deposit btc ltc or dash gives error when pressing deposit button

restart accountserver refresh page after 1 min 
can press deposit button wallet adress shows up 
logout trader account 1 login to trader account 2 go to wallet press deposit btc or ltc or dash error shows up again

**Comment by Lightningcash-dev** [comment]
Exact same error here.

**Comment by 3s3s** [comment]
Hi
please update accountserver. Should be fixed this

**Comment by christophergidlof** [comment]
That fixed it
