### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by dhhhfgnvn** [3s3s/opentrade#315]
Hi, I'm getting this error :
ubuntu@base-server:~/opentrade/server$ sudo node main.js
SSL Proxy listening on port 443
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:40545
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

Does anybody have any ideea?

**Comment by dhhhfgnvn** [comment]
I seem to have solved it. It is more of these path issues. Say, you have the installation at /home/thisisme/opentrade then have symlinks to that directory from /home/opentrade and /root/opentrade.

**Comment by xcelr** [comment]
Hey how did you go about fixing this?
