### ISSUE TITLE
Cancel the order without subtracting the commission

### ISSUE THREAD

**Issue by ach-group** [3s3s/opentrade#320]
Hello guys,

how can i customize it so that order cancellation does not cut commission trade charges and balance is back to normal.

If the deduction continues despite the canceled trade this is not comfortable for traders causing double the cost.

hope someone helps.

Best regards.

**Comment by 3s3s** [comment]
After the order cancelation comissions should be returned and balance should go back to normal. 
https://github.com/3s3s/opentrade/blob/master/server/modules/users/orders.js#L75
