### ISSUE TITLE
Is latest SQL inject bug fix legit?

### ISSUE THREAD

**Issue by ShorelineCrypto** [3s3s/opentrade#332]
Hi 3s3s, 

I noticed that latest commit a3eb3c645cfd1f3d310c10e4fb1f2f64a4d5e45e  in master branch claimed to fix the SQL inject hack bug.  The person who committed is unknown, not verified.  Is this commit legit?

Just read through the commit, it appears that it mainly changed two part.  One is "func"  becomes " async func".  Another part is added "await" before  utils.GetCoinFromTicker function.  This function also modified. 

Thanks.

**Comment by 3s3s** [comment]
Hi

yes this is a verified update
