### ISSUE TITLE
12.6.0 development testing into Https - Loading issue "Your Balance" +"chat" const loading loop

### ISSUE THREAD

**Issue by Dkpe** [3s3s/opentrade#353]
Good day

Don't know if anyone recently tried to load Opentrade on 12.6.0. Currently having a issue when trying to put Opentrade into development testing .

constants.js is set to the domain name 
const DOMAIN = '**website.com**';

Everything loads 100% on the local
Https://127.0.0.1 / Https://localhost

However when i use the Https://website.com with the correct ssl certs i get a forever constant loading as seen in image below 

![debug](https://user-images.githubusercontent.com/66471698/83868764-c04e2300-a72b-11ea-851f-7ec35efd77c3.png)

If you know a fix let me know .

**Comment by wwwcase** [comment]
cat /etc/hosts
127.0.0.1 website.com

**Comment by Dkpe** [comment]
@wwwcase I meant to close this but this is quite a interesting issue . 

When you use for example 
Domain-ex.com 

The "-" cause it not to load . 

I changed made a fix and all working now
