### ISSUE TITLE
Help, PoS scrypt coin withdraw does not work?

### ISSUE THREAD

**Issue by ShorelineCrypto** [3s3s/opentrade#367]
Hello kzv and all fellow opentrade admin friends:

I have setup PoS scrypt coin in my exchange and all the deposit worked fine. But withdraw I think no one including members tested it out.  I tried today for withdraw, and found below errors on confirmation:
 Withdraw error (3): Narration must be 24 characters or less.

This coin information is selfiecoin (SLFI), Ann page and github source is at:
https://bitcointalk.org/index.php?topic=977167.0

Can someone help me out on how to fix the withdraw errors?  I am running an older version of OpenTrade before Coupon feature, and with all the security commits patched up to date.

**Comment by ShorelineCrypto** [comment]
I have looked at the Selfiecoin README, it was PPcoin clone, not DASH clone:
SelfieCoin

Copyright (c) 2014 SelfieCoin Developers
Copyright (c) 2014 BlackCoin Developers
Copyright (c) 2013 NovaCoin Developers
Copyright (c) 2011-2012 PPCoin Developers

**Comment by 3s3s** [comment]
Try to change this line
https://github.com/3s3s/opentrade/blob/master/server/modules/users/wallet.js#L804

to
[userAccount, address, utils.roundDown(amount), coin.info.minconf || 3, comment+"it seems that comment should by more than 24 charactes in some coins (like SLFI) "];

**Comment by ShorelineCrypto** [comment]
I am on this commit with all security patched up to date. 
https://github.com/3s3s/opentrade/commit/9f9d69adda07282957aca20d12e89e1a14acc4e2

My fix for the same corresponding line in the old commit:
 [userAccount, address, (amount*1).toFixed(7)*1, coin.info.minconf || 3, comment+"it seems that comment should by more than 24 charactes in some coins (like SLFI) "];

I tried this fix and restart openTrade, it does not work. Withdraw of SLFI still has same error on confirmation:
Withdraw error (3): Narration must be 24 characters or less.

**Comment by 3s3s** [comment]
"24 characters or less"
my bad (
try it change to
[userAccount, address, utils.roundDown(amount), coin.info.minconf || 3, "should be < 24"];

**Comment by ShorelineCrypto** [comment]
Awesome. this fixed  SLFI Narration 24 charactes error. Actually, this comment narration shows up SLFI QT wallet Narration field upon exchange withdraw, cool.
