### ISSUE TITLE
Database folder empty 

### ISSUE THREAD

**Issue by khanmos12** [3s3s/opentrade#381]
I have zero log files but, opentrade/server/database - is empty, hence nothing is working. Dev, can you give me a solution to this?

**Comment by elmaedesistemas** [comment]
hi!
i have the same problem, maybe someone can attach us the sqlite file, please?

**Comment by elmaedesistemas** [comment]
@khanmos12 i have a version preview of this repository where i have the sqlite file, send me an email to dmejia1204@gmail.com for send you the file and close the issue!!!

**Comment by khanmos12** [comment]
Hi, I have sent you an email requesting for the file.

**Comment by khanmos12** [comment]
Please send files to my email: khanmos12@gmail.com

**Comment by elmaedesistemas** [comment]
Hi Khan i send you the files to your email, when you receive the files please close the issue!
Regards! :)

**Comment by yaboiroabi** [comment]
**### I am having this same issue... please help**
 @khanmos12 @coffescript please help

**Comment by amankakar** [comment]
@khanmos12  can you please send file to me at email :[ amankhan1017@gmail.com](url). thanks in advance/
