### ISSUE TITLE
App log are not displaying on terminal

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#39]
After the recent bug fix when I run `sudo node main.js` It displays nothing but the app works perfectly.
```
kartx@ubuntu:~/Download/opentrade/server$ sudo node main.js 
▮
```
I have to use `sudo NODE_DEBUG=cluster,net,http,fs,tls,module,timers node main.js` to get the output log from the server.

**Comment by 3s3s** [comment]
uncomment this
https://github.com/3s3s/opentrade/blob/master/server/main.js#L16
https://github.com/3s3s/opentrade/blob/master/server/main.js#L17

**Comment by knkrth** [comment]
Thanks.
