### ISSUE TITLE
Unable To Conform E-Mail Verfication

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#43]
Hi, After the new update I'm unable to verify my account on signup. It keeps saying,
```
Something wrong ((
Please try Sign up again.
```
I'm the only one having this issue or not?

**Comment by 3s3s** [comment]
Try to change https://github.com/3s3s/opentrade/blob/master/server/modules/registration/signup.js#L118

utils.render(res, 'pages/registration/signup_confirm', {error: true, message: 'Something wrong (( Please try again. ('+(err.message || JSON.stringify(err))+')'});

It will show the error

**Comment by knkrth** [comment]
I made changes as you suggested still same message & No other error has been displayed except.
```
Something wrong ((
Please try Sign up again.
```
On the server log I got,
```
dIjWR0ybt/JqAPaKs=Q2GkrmiCdYLlKbq2JINwcZIE40%3D
{"dIjWR0ybt/JqAPaKsQ2GkrmiCdYLlKbq2JINwcZIE40%3D":{"body":{"username":"admin","email":"admin@admin.com","password1":"admin","password2":"admin"},"time":1527577857343}}
```
After clicking the link.

**Comment by knkrth** [comment]
Before the merge #42 I can conform the e-mail verification without any problem.

**Comment by 3s3s** [comment]
Try to change
https://github.com/3s3s/opentrade/blob/master/server/views/pages/registration/signup_confirm.ejs#L17
https://github.com/3s3s/opentrade/blob/master/server/views/pages/registration/signup_confirm.ejs#L18
https://github.com/3s3s/opentrade/blob/master/server/views/pages/registration/signup_confirm.ejs#L19

```
      <div class="row" <% var fail = ''; var errMessage = message || "(unknown)"; if (!error) fail = 'style="display:none;"'%> <%- fail %>>
        <div class="offset2 col-md-6">
            <h2>Something wrong (( <%- errMessage%></h2>
```

And
https://github.com/3s3s/opentrade/blob/master/server/views/pages/registration/signup_confirm.ejs#L17

```
console.log('Something wrong (( Please try again. ('+(err.message || JSON.stringify(err))+')');
return;
```

**Comment by knkrth** [comment]
Now I got a internal mail server error `Error with your mail server: queryMx ETIMEOUT` I think its my mail server problem. Right now I leave this issue open, If no one else have the same problem means we can close this issue after a couple of days.
