### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by vitorgamer58** [3s3s/opentrade#5]
We could include some documentation, some tutorial teaching how to start building your own exchange and how to modify the coins, maybe we could do something in the repository Wiki, what do you think? because as my knowledge is low in this area I do not know where to start. thank you.

**Comment by 3s3s** [comment]
Hi 
I do not have time to do the documentation at all
It will be fine if someone writes the documentation and/or Wiki

**Comment by vitorgamer58** [comment]
yes, if you can give me a little about how to start, some small tutorial, I could build a Redme or Wiki, I'm trying to create an exchange for a cryptonight currency.

**Comment by charnasol** [comment]
Yes base starting instructions would be good. Maybe first few steps. As nice looking exchange. I think many would help.

**Comment by 3s3s** [comment]
Created readme.md in the test branch

**Comment by vitorgamer58** [comment]
excellent, very good, I barely see the time to test the implementation on my notebook, who knows I'll open an exchange? I'll leave a link to the github code.

**Comment by charnasol** [comment]
their are several things missing in the installation. The framework is their, but many other parts not. And some of the install instructions are off.

**Comment by vitorgamer58** [comment]
I agree, but I did, I'll pull a request soon.

**Comment by charnasol** [comment]
If you have some of the missing pieces which includes the trading, please let me know.

**Comment by vitorgamer58** [comment]
Yes, it's missing a part, how to add trade pairs?

**Comment by charnasol** [comment]
That would be great to find out. Maybe put in a request for information? So we all know how to add it ina  timely manner.

**Comment by vitorgamer58** [comment]
exactly, I already managed to install the exchange, only the pairs are missing

**Comment by charnasol** [comment]
Hi we may have the coding for the pairs. And we are also working on some additions. We will keep dev’ing this up when we can.

**Comment by vitorgamer58** [comment]
Top, regards to all the developers, I know that creating an exchange like this is not easy.

**Comment by charnasol** [comment]
we did not create but will keep helping to dev and code if we get the support. Maybe some donations along the way do we can make more improvements. By end of week, I think we may have coding needed for coin pairs/trading. 
I will post a btc address for donations.

**Comment by 3s3s** [comment]
I have updated Readme. Please try add pairs as described.
