### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#53]
Add URL for separate coins with their ticker like,
```
https://yobit.net/en/trade/ETH/BTC
https://yobit.net/en/trade/BCC/BTC
https://yobit.net/en/trade/LTC/DOGE
```
![ticker_url](https://user-images.githubusercontent.com/12738581/41733539-b7638676-75a1-11e8-88cf-1f8707c86a0e.png)

So that its easy to share & add on other sites.

**Comment by 3s3s** [comment]
done

**Comment by trungtt1981bacoor** [comment]
@knkrth 

Pls allow me to have a few questions.

Have you successfully got ETH support for OpenTrade?
Is it possible if we manually enhance/modify OpenTrade source code so that it can support ETH?

Thanks for any feedback from you

**Comment by knkrth** [comment]
@trungtt1981bacoor Yes it is. But you need to modify alot of things to add ETH to opentrade.
