### ISSUE TITLE
Can it be used with MYSQL database ?

### ISSUE THREAD

**Issue by miranos** [3s3s/opentrade#58]
Can OpenTrade be used with MYSQL database ?

For easy management !

**Comment by 3s3s** [comment]
Yes, if you will made relevant changes in this file https://github.com/3s3s/opentrade/blob/master/server/database.js

**Comment by rraallvv** [comment]
I'm interested too, but it seems MySQL doesn't support parallelization. So I guess those would have to be made with a separate connection to de db each.
