### ISSUE TITLE
Typo in fees page

### ISSUE THREAD

**Issue by bihonglu** [3s3s/opentrade#60]
This was a feedback from my ShorelineCrypto user. 

daniba - Today at 6:25 PM
There is your typo under "Withdraw Commission": The sentence "To ensure withdraw we are freeze the minimum balance" should be rephrased. Maybe "To ensure the withdrawal, we will freeze the minimum balance" Or smth like that :wink:

**Comment by daygle** [comment]
Why don't you submit a pull request?

**Comment by bihonglu** [comment]
Good point.  Never done pull request, will do in the future for similar issues.
