### ISSUE TITLE
Add API to get exchange summery

### ISSUE THREAD

**Issue by jonn4y** [3s3s/opentrade#68]
How easy would it be to create an API that outputted exchange statistics for use on websites like CMC etc.

something like 'onGetExchangeSummery'
that would output something like this:

{
	"success" : true,
	"message" : "",
	"result" : [{
			"TotalMarkets" : "22",
			"24v" : 0.01350000
		        }
        ]
    }

Where the 24v would be all the markets 24hr volume converted into the base currency (MC or BTC) then outputted as one total 24 hour volume for the exchange as a whole.

Thanks

**Comment by 3s3s** [comment]
done

**Comment by jonn4y** [comment]
wow that was fast, thank you very much
