### ISSUE TITLE
Chat Not Working After Update

### ISSUE THREAD

**Issue by daygle** [3s3s/opentrade#75]
Hi,

Just letting you know chat isn't working after recent update.

Steps to replicate:-
1. Delete a single chat message with the X button.
2. After this my chat went blank, and now fails to load.

**Comment by jonn4y** [comment]
@3s3s my chat has gone too, and any new messages are not saved either after you refresh the page the new messages are gone and when you check debug you cant even see the entry being made to the db, any ideas?

**Comment by 3s3s** [comment]
I have no troubles with chat. 
Try to stop exchange, delete the table "KeyValue", then start again. Maybe this will help?

**Comment by daygle** [comment]
@3s3s I think you will have trouble, delete a single message and see what happens.

**Comment by jonn4y** [comment]
i stopped the exchange and removed the entire KeyValue table, restarted and added a few messages, deleted one and the rest are still there so its sorted the issue for me, give it a try @daygle

**Comment by daygle** [comment]
@3s3s Your recent changes to the websocket broke it, I reverted these changes for that file and it worked again.

**Comment by daygle** [comment]
@jonn4y really? I feel like I restarted the exchange multiple times and also deleted the KeyValue. Maybe I should re-add the changes back for the websocket.js, restart and try again.

**Comment by jonn4y** [comment]
@daygle i backed up my database and transferred it to my mac, opened it in DB Browser and removed the table, keeping the new web socket changes i re-uploaded the DB, restarted and tested and now seems to be working fine

**Comment by daygle** [comment]
Ok I'll close this issue now, seems to be working.

**Comment by TheRealHotSwap** [comment]
I am having this issue now. No chat messages save for me after refresh.
