### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#85]
Hi, Can you add "Make this coin as a source coin" option on add coin section in admin page so that we can have multiple source coin like BTC-LTC, LTC-DOGE, DOGE-MC on other exchanges.

**Comment by ZSmartDev** [comment]
Nice

**Comment by Tr0j4n9** [comment]
So you mean multiple trade pairs?

**Comment by knkrth** [comment]
@Tr0j4n9 Yes.

**Comment by Tr0j4n9** [comment]
Yes, That would be cool.

**Comment by knkrth** [comment]
Duplicate of #216
