### ISSUE TITLE
How to add a new coin on opentrade script?

### ISSUE THREAD

**Issue by ThemeWebZone** [3s3s/opentrade#86]
My opentrade script installation is complete. Now I want to add some coin on our opentrade script. Now my question is what is the process to add bitcoin or ethereum coin on our script???

![image](https://user-images.githubusercontent.com/18362027/43989684-a438314a-9d70-11e8-97ec-cbd402cab253.png)

**Comment by lightrain125** [comment]
I can not install the script. Can you help me?

**Comment by ThemeWebZone** [comment]
Sure. You can join me on skype. we'll discuss it.

**Comment by lightrain125** [comment]
Please skype id

**Comment by ThemeWebZone** [comment]
Here is my id (romel.mahi.badhon.)

**Comment by jonn4y** [comment]
you cannot add ethereum, all is explained in the instructions, if you dont know how to setup wallets then i would advise an exchange isn't for you, you will be dealing with peoples money

**Comment by ThemeWebZone** [comment]
Ok, How can I add another currency to my script?

**Comment by jonn4y** [comment]
change this line to the coin you want as the main coin that other coins will be paired against
https://github.com/3s3s/opentrade/blob/master/server/constants.js#L20

i.e. change it to bitcoin

then set up the wallets you need following the instructions
