### ISSUE TITLE
Add Coupon Option To Users

### ISSUE THREAD

**Issue by knkrth** [3s3s/opentrade#87]
Hi, By providing a create coupon option to users they can send coins to other users without the transaction fee & It is easy & secure. Those coupon can also used as a payment like yobit code https://yobit.net/en/yobicodes/

**Comment by jonn4y** [comment]
This was added in the last updates
users can withdraw to voucher then send the code to other users

<img width="643" alt="screen shot 2018-08-13 at 11 41 11" src="https://user-images.githubusercontent.com/726705/44027294-d37d24aa-9eed-11e8-81cc-eceddf90a769.png">

**Comment by knkrth** [comment]
I'm sorry I didn't see it thanks for pointing out :) My bad :|
