### ISSUE TITLE
Prevent RPC Calls in 5 Seconds Issue

### ISSUE THREAD

**Issue by daygle** [3s3s/opentrade#93]
Referring to the section of code "Prevent to call same RPC more than once per 5 sec (for one user and one coin)". Is anyone else experiencing issues with this?

https://github.com/3s3s/opentrade/blob/f89981a062912cd4c3e2e1ada655724901010620/server/modules/rpc.js#L104

I ended up disabling this section as my users balances was failing to update with this code. Although is says 'for one user and one coin' this doesn't seem to be the case.

Balances are pulled for whatever wallets it is able to obtain details in the first 5 seconds then any subsequent wallets (after the 5 seconds) the code prevents wallet updates.

**Comment by 3s3s** [comment]
No need to disable all section. Change this line https://github.com/3s3s/opentrade/blob/f89981a062912cd4c3e2e1ada655724901010620/server/modules/rpc.js#L109
5000 (5 sec) to 0

**Comment by daygle** [comment]
I'll close this issue for the time being.
